In [1]:
%pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [2]:
import nltk
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
# from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from nltk.corpus import stopwords
import string
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.naive_bayes import MultinomialNB
# from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [3]:
spam =pd.read_csv("spam.csv", encoding="ISO-8859-1")

In [4]:
spam.head(10)

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
spam["v1"] = le.fit_transform(spam["v1"])

In [7]:
spam.head(10)

v1                                                 v2
0   0  Go until jurong point, crazy.. Available only ...
1   0                      Ok lar... Joking wif u oni...
2   1  Free entry in 2 a wkly comp to win FA Cup fina...
3   0  U dun say so early hor... U c already then say...
4   0  Nah I don't think he goes to usf, he lives aro...
5   1  FreeMsg Hey there darling it's been 3 week's n...
6   0  Even my brother is not like to speak with me. ...
7   0  As per your request 'Melle Melle (Oru Minnamin...
8   1  WINNER!! As a valued network customer you have...
9   1  Had your mobile 11 months or more? U R entitle...

In [8]:
spam.shape

(5572, 2)

In [9]:
spam.columns

Index(['v1', 'v2'], dtype='object')

In [10]:
print(spam.isnull().sum())

v1    0
v2    0
dtype: int64


In [11]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Michigan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [12]:
def process(txt):
    no_punct = [i for i in txt if i not in string.punctuation]
    no_punct = ''.join(no_punct)

    clean_words = [word for word in no_punct.split() if word.lower() not in stopwords.words('english')]
    return clean_words


In [13]:
#tokenization
spam['v2'].head().apply(process)

0    [Go, jurong, point, crazy, Available, bugis, n...
1                       [Ok, lar, Joking, wif, u, oni]
2    [Free, entry, 2, wkly, comp, win, FA, Cup, fin...
3        [U, dun, say, early, hor, U, c, already, say]
4    [Nah, dont, think, goes, usf, lives, around, t...
Name: v2, dtype: object

In [16]:
mail= CountVectorizer(analyzer=process).fit_transform(spam['v2'])

In [17]:
xtrain, xtest, ytrain, ytest = train_test_split(mail, spam['v1'], test_size=0.20, random_state=0)
print(mail.shape)

(5572, 11304)


In [18]:
classifier = MultinomialNB().fit(xtrain, ytrain)

In [19]:
print(classifier.predict(xtrain))
print(ytrain.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [20]:

pred = classifier.predict(xtrain)
print(classification_report(ytrain, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(ytrain, pred))
print("Accuracy: \n", accuracy_score(ytrain, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3876
           1       0.98      0.98      0.98       581

    accuracy                           0.99      4457
   macro avg       0.99      0.99      0.99      4457
weighted avg       0.99      0.99      0.99      4457


Confusion Matrix: 
 [[3864   12]
 [  12  569]]
Accuracy: 
 0.9946152120260264


In [21]:
print(classifier.predict(xtest))

print(ytest.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [22]:

pred = classifier.predict(xtest)
print(classification_report(ytest, pred))
print()
print("Confusion Matrix: \n", confusion_matrix(ytest, pred))
print("Accuracy: \n", accuracy_score(ytest, pred))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97       949
           1       0.81      0.93      0.87       166

    accuracy                           0.96      1115
   macro avg       0.90      0.95      0.92      1115
weighted avg       0.96      0.96      0.96      1115


Confusion Matrix: 
 [[914  35]
 [ 12 154]]
Accuracy: 
 0.957847533632287
